### PR TITLE
Formalize Partitioned streams

### PR DESCRIPTION
**Pull request by woksin**
Formalizes partitioned and unpartitioned streams by having two different filters services

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1172328344435435)

### CODE REVIEW

**Comment by woksin** [comment]
I think we have to wait a bit for this

**Review by jakhog — CHANGES_REQUESTED** [review]
It looks correct - but I'm not feeling the names. I like better dropping the `Unpartitioned` part from, so that there are `Filter`s and `PartitionedFilter`s. In my head a partitioned filter is an extension of a filter, kind of like a `PublicFilter` is, and if we ever wanted more, that naming sounds nice.

Also I would keep a single `service` for all the filters as well, and have separate methods on them in stead of splitting up the service.

**Comment by woksin** [comment]
Okay, we can try that naming. I agree that the names needs some love. 

Keeping them in the same service also makes sense. I'll do that, and that also reflects in the Runtime code as well. I have pull requests there as well, I'll change them when this is pulled in :)

**Comment by woksin** [comment]
> It looks correct - but I'm not feeling the names. I like better dropping the `Unpartitioned` part from, so that there are `Filter`s and `PartitionedFilter`s. In my head a partitioned filter is an extension of a filter, kind of like a `PublicFilter` is, and if we ever wanted more, that naming sounds nice.
> 
> Also I would keep a single `service` for all the filters as well, and have separate methods on them in stead of splitting up the service.

This should solve all your problems, @jakhog 
https://github.com/dolittle-runtime/Contracts/pull/16/commits/6fa79e25fd2adc9cd119c2c0654566503387e80b

Edit:
Pulled the trigger too soon. This fixes the fix https://github.com/dolittle-runtime/Contracts/pull/16/commits/301506a8a9e8c099f6e7d94feeba2e4eebcfc2f8

**Review by jakhog — APPROVED** [review]
Looks good to me!

**Pull request merged**
