### PR TITLE
artifact and type => eventType

### PR DESCRIPTION
**Pull request by woksin**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1140654762299587/1193026962044002)

### CODE REVIEW

**Comment by woksin** [comment]
This is a patch of the contracts, but for the built javascript and .Net packages this is a major change... So releasing this will break applications using latest version of the Contracts when the SDKs and Runtime is not updated.

But I guess that we should strive for updating the SDKs and Runtime asap after this is released :)

**Review by jakhog — CHANGES_REQUESTED** [review]
Lets hold this for a little while. As you say it's a breaking change for the generated code - which in turn means a breaking change for the SDKs, but not a breaking change for the gRPC contract between the Runtime and the SDKs. So I think we want to do a few more things here to help with detecting gRPC contract versions.

**Comment by woksin** [comment]
Changed this to a major release

**Comment by jakhog** [comment]
Changing this over so we merge it in with the EventSource as string major bump.

**Review by jakhog — APPROVED** [review]

**Pull request merged**
